"""empty message

Revision ID: 28ab778465bd
Revises: None
Create Date: 2016-01-20 14:09:11.219150

"""

# revision identifiers, used by Alembic.
revision = '28ab778465bd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hit_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('turk_input', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_hit_hit_id'), 'hit', ['hit_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hit_hit_id'), table_name='hit')
    op.drop_table('hit')
    ### end Alembic commands ###
