"""empty message

Revision ID: 37e042f80260
Revises: 48bbb1749e23
Create Date: 2016-02-08 15:20:53.234617

"""

# revision identifiers, used by Alembic.
revision = '37e042f80260'
down_revision = '48bbb1749e23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'hit_title_key', 'hit', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'hit_title_key', 'hit', ['title'])
    ### end Alembic commands ###
