"""empty message

Revision ID: 48bbb1749e23
Revises: 4bf2f51aca59
Create Date: 2016-02-05 14:47:22.189930

"""

# revision identifiers, used by Alembic.
revision = '48bbb1749e23'
down_revision = '4bf2f51aca59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hit', 'created_at')
    ### end Alembic commands ###
