"""empty message

Revision ID: 4bf2f51aca59
Revises: 6e2d768c9cc8
Create Date: 2016-02-05 10:29:31.822444

"""

# revision identifiers, used by Alembic.
revision = '4bf2f51aca59'
down_revision = '6e2d768c9cc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit', sa.Column('instructions', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hit', 'instructions')
    ### end Alembic commands ###
