"""empty message

Revision ID: 6e2d768c9cc8
Revises: 24a2e44a3fc9
Create Date: 2016-02-05 08:21:04.368713

"""

# revision identifiers, used by Alembic.
revision = '6e2d768c9cc8'
down_revision = '24a2e44a3fc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit', sa.Column('bounty', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hit', 'bounty')
    ### end Alembic commands ###
