"""empty message

Revision ID: 8f0ded4d2851
Revises: ad89f968c2a8
Create Date: 2016-04-01 03:00:40.957666

"""

# revision identifiers, used by Alembic.
revision = '8f0ded4d2851'
down_revision = 'ad89f968c2a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_type')
    ### end Alembic commands ###
