"""empty message

Revision ID: 9e6cca2de0f0
Revises: 28ab778465bd
Create Date: 2016-01-25 23:18:30.501778

"""

# revision identifiers, used by Alembic.
revision = '9e6cca2de0f0'
down_revision = '28ab778465bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
