"""empty message

Revision ID: a7f34ea70a46
Revises: f7409baaad2c
Create Date: 2016-02-27 00:10:03.970221

"""

# revision identifiers, used by Alembic.
revision = 'a7f34ea70a46'
down_revision = 'f7409baaad2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'on_campus')
    op.drop_column('event', 'all_day')
    op.drop_column('event', 'registration_req')
    op.drop_column('event', 'virtual')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('virtual', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('registration_req', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('all_day', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('on_campus', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
