"""empty message

Revision ID: a99421b664f8
Revises: 37e042f80260
Create Date: 2016-02-08 15:46:26.900078

"""

# revision identifiers, used by Alembic.
revision = 'a99421b664f8'
down_revision = '37e042f80260'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit', sa.Column('keywords', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hit', 'keywords')
    ### end Alembic commands ###
