"""empty message

Revision ID: ad89f968c2a8
Revises: f13e332251b4
Create Date: 2016-04-01 03:00:00.212613

"""

# revision identifiers, used by Alembic.
revision = 'ad89f968c2a8'
down_revision = 'f13e332251b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    ### end Alembic commands ###
