"""empty message

Revision ID: d0139c585f81
Revises: a7f34ea70a46
Create Date: 2016-02-27 00:10:35.245085

"""

# revision identifiers, used by Alembic.
revision = 'd0139c585f81'
down_revision = 'a7f34ea70a46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('all_day', sa.String(length=16), nullable=True))
    op.add_column('event', sa.Column('on_campus', sa.String(length=16), nullable=True))
    op.add_column('event', sa.Column('registration_req', sa.String(length=16), nullable=True))
    op.add_column('event', sa.Column('virtual', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'virtual')
    op.drop_column('event', 'registration_req')
    op.drop_column('event', 'on_campus')
    op.drop_column('event', 'all_day')
    ### end Alembic commands ###
