"""empty message

Revision ID: f13e332251b4
Revises: 86308fae1b55
Create Date: 2016-03-27 22:03:15.439645

"""

# revision identifiers, used by Alembic.
revision = 'f13e332251b4'
down_revision = '86308fae1b55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('google_location_id', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'google_location_id')
    ### end Alembic commands ###
