"""empty message

Revision ID: f1803263824d
Revises: d0139c585f81
Create Date: 2016-03-26 23:48:11.724848

"""

# revision identifiers, used by Alembic.
revision = 'f1803263824d'
down_revision = 'd0139c585f81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hit', 'school')
    op.drop_column('hit', 'turk_input')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hit', sa.Column('turk_input', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hit', sa.Column('school', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    ### end Alembic commands ###
